server:
  port: 8081

spring:
  application:
    name: api-gateway

# URLs de los microservicios por bounded context
services:
  order:
    url: http://localhost:8082
  payment:
    url: http://localhost:8084
  shipping:
    url: http://localhost:8083
  inventory:
    url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info