server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${SERVICES_ORDER_URL:http://localhost:8082}
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: ${SERVICES_PAYMENT_URL:http://localhost:8084}
          predicates:
            - Path=/payments/**
        - id: shipping-service
          uri: ${SERVICES_SHIPPING_URL:http://localhost:8083}
          predicates:
            - Path=/shipping/**
        - id: inventory-service
          uri: ${SERVICES_INVENTORY_URL:http://localhost:8085}
          predicates:
            - Path=/inventory/**
        - id: eda-service
          uri: ${SERVICES_EDA_URL:http://localhost:8080}
          predicates:
            - Path=/customer/**

services:
  order:
    url: ${SERVICES_ORDER_URL:http://localhost:8082}
  payment:
    url: ${SERVICES_PAYMENT_URL:http://localhost:8084}
  shipping:
    url: ${SERVICES_SHIPPING_URL:http://localhost:8083}
  inventory:
    url: ${SERVICES_INVENTORY_URL:http://localhost:8085}
  eda:
    url: ${SERVICES_EDA_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info